version: '3'
services:
  tosca-syntax:
    # will build ./syntax/Dockerfile
    build:
      context: ./syntax
    ports:
     - "5000:5000"

  ansible-workflow:
    # will build ./workflow/Dockerfile
    build:
        ./workflow
    ports:
      - "5001:5000"
  
  opa-server:
    # will start opa server
    image: openpolicyagent/opa:0.25.1
    ports:
      - "8181:8181"      
    command:
      - "run"
      - "--server"
      - "--log-level=debug"
      
